name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Clean previous builds
      run: dotnet clean -c Release

    - name: Publish artifacts
      if: success()
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Create ZIP file
      if: success()
      run: |
        cd ${{ github.workspace }}/publish
        if (Test-Path "../published-app.zip") { Remove-Item "../published-app.zip" }
        powershell Compress-Archive -Path * -DestinationPath ../published-app.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-app-zip
        path: ${{ github.workspace }}/published-app.zip

    - name: Add build metadata
      if: success()
      run: |
        echo "Build Number: $GITHUB_RUN_NUMBER" > ${{ github.workspace }}/publish/build_metadata.txt
        echo "Commit: $GITHUB_SHA" >> ${{ github.workspace }}/publish/build_metadata.txt
